version:     "0001--22-Feb-2023"
copyright:   "2023"
author:      "Linus A. W."
title:       "OS231: Operating Systems 2023-1"
githublink:  "https://github.com/linusabhyasaui/os231/"
myloglink:   "TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
